# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b271a9baf2331a898495526201b472fea59603c17feded3eb9e5af045f0ff03bada81b8957a35545bebe3f6a2f1e0c68cdadd468406fb06181e3b597752d02e7

test:
  secret_key_base: 44a1f941e174cbd7f8f3da70e1238f4243a52e8f7280986be5628e50cd6e56cd57aee061d64f8879549c341d01b613d71a2d0441c7d0ba2c7207bd729ed99b81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
